[project]
name = "linkedin_solvers"
version = "0.2.0"
description = "Solvers for linkedin games"
authors = [
    {name = "Daniel Banks"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black (>=26.5.1,<27.0.0)",
    "ruff (>=0.16.8,<0.17.0)",
    "playwright (>=1.63.0,<2.0.0)"
]

[project.scripts]
linkedin_solvers = "run:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "flake8 (>=7.3.0,<8.0.0)"
]